# Banner Tool Server and client !
rd, gn = '\033[00;31m', '\033[00;32m'
print ("""
033[00;32m
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXWWMMMMMWNXKXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNkdOXWMMMMMMMMMWXOdkNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWO;cKMMMMMMMMMMMMMMMKc:OWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWx.;KMMMMMMMMMMMMMMMMMK,.kWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMO. \033[01;33moWMMMMMMMMMMMMMMMMMWl '0MMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWl  lWMMMMMWNNNNNWMMMMMNc  oWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNc  '0WXko:,'...';coOXWO.  lWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWo   'kd. .';:::;'. .dx'  .dWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWX0l.   .;cdKWMMMMMWKdc;.   .dKNWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW0o;.         .:ldKW0dl;.        .':dKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWO;.  .....        ,kNx'        .....  .c0WMMMMMMMMMMMMM
MMMMMMMMMMMMMNo..cx0KX0o;cl:.   lXMMMXl   .;l:;l0K0Od:..dNMMMMMMMMMMMM
MMMMMMMMMMMMNl'oXWMMMMK, .kWKo':OWMMMWO;'l0Wk. '0MMMMWKl'oNMMMMMMMMMMM
MMMMMMMMMMMMk:OWMMMMMMNc  cNMWXo,;lll;,oKWMNl  cNMMMMMMWk:kMMMMMMMMMMM
MMMMMMMMMMMWxkWMMMMMMMM0,  cXMWx.     .dWMXl. '0MMMMMMMMWkxWMMMMMMMMMM
MMMMMMMMMMMW0XMMMMMMMMMMK:  'oKO'     'OKd,  ;0MMMMMMMMMMK0WMMMMMMMMMM
MMMMMMMMMMMMNNMMMMMMMMMMMNk;. :d.     .x:  ,xNMMMMMMMMMMMNNMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0xx:       :doONMMMMMMMMMMMMMWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;    .    :KWMMMMMMMMMMMMMMMMMMMMMMMMMMM
\033[00;31mMMMMMMMMMMMMMMMWNXXWMMMMMWXkc.  .ckKk;.  .lONMMMMMMWNXNWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWNK0kxolc;'..':dKWMMMW0o;...';codxk0KXWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNK0OkkO0KNMMMMMMMMMMWX0OxxxxO0XWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""")
